package dal;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import model.Ricetta;

public class FintoDatabase {

	public static List<Ricetta> ricetteBase = new ArrayList<>(
			
			Arrays.asList(
					new Ricetta("Cannarozzetti allo zafferano"),
					new Ricetta("Spaghetti all'abruzzese"),
					new Ricetta("Timballo ai finocchi"),
					new Ricetta("Fettuccine all'abruzzese"),
					new Ricetta("Cannelloni all'abruzzese"),
					new Ricetta("Fettuccine ai peperoni"),
					new Ricetta("Fregnacce"),
					new Ricetta("Maccheroni alla molinara"),
					new Ricetta("Maccheroni alla chitarra"),
					new Ricetta("Tagliatelle al sugo di lumache"),
					new Ricetta("Tagliatelle al baccalà"),
					new Ricetta("Pasta e fagioli"),
					new Ricetta("Cavatelli con pecorino e rucola"),
					new Ricetta("Cavatelli alle cime di rapa"),
					new Ricetta("Fusilli alla salsiccia"),
					new Ricetta("Fusilli con la mollica"),
					new Ricetta("Grano al sugo"),
					new Ricetta("Orecchiette alla materana"),
					new Ricetta("Lagane e ceci"),
					new Ricetta("Orecchiette con le rape"),
					new Ricetta("Spaghetti di maratea"),
					new Ricetta("Strozzapreti alla potentina"),
					new Ricetta("Pasta ai ricci di mare"),
					new Ricetta("Pasta e Broccoli"),
					new Ricetta("Pennette alle Verdure Piccanti"),
					new Ricetta("Cannaruozzi 'ncipuddati"),
					new Ricetta("Spaghetti con carciofi"),
					new Ricetta("Riso alle mandorle"),
					new Ricetta("Tagliatelle alla reggina"),
					new Ricetta("Bucatini con la mollica"),
					new Ricetta("Bucatini con lo stocco"),
					new Ricetta("Bucatini col finocchietto selvatico"),
					new Ricetta("Spaghetti con le alici"),
					new Ricetta("Fusilli al cedro"),
					new Ricetta("Maccaruni ara turanisi"),
					new Ricetta("Ravioli con lo stocco"),
					new Ricetta("Risotto con lo stocco"),
					new Ricetta("Spaghetti al nero di seppia"),
					new Ricetta("Lagane e ceci"),
					new Ricetta("Gnocchi alla caprese"),
					new Ricetta("Maltagliati alla napoletana"),
					new Ricetta("Spaghetti con le vongole"),
					new Ricetta("Pasta e castagne"),
					new Ricetta("Spaghetti ai firarielli"),
					new Ricetta("Pasta mista con fave e pancetta"),
					new Ricetta("Tagliatelle al ragù"),
					new Ricetta("Tortellini alla bolognese"),
					new Ricetta("Gnocchi di patate"),
					new Ricetta("Cappellacci di zucca"),
					new Ricetta("Bassotti"),
					new Ricetta("Garganelli con ragù alla romagnola"),
					new Ricetta("Gramigna con la salsiccia"),
					new Ricetta("Anolini di carne parmensi"),
					new Ricetta("Cappelletti alla bolognese"),
					new Ricetta("Cappelletti all'emiliana"),
					new Ricetta("Cappelletti di magro romagnoli"),
					new Ricetta("Cappelletti pasticciati"),
					new Ricetta("Cappelletti romagnoli"),
					new Ricetta("Passatelli reggiani"),
					new Ricetta("Pasta rasa reggiana"),
					new Ricetta("Risotto alla parmigiana"),
					new Ricetta("Risotto all'imolese"),
					new Ricetta("Risotto con la zucca"),
					new Ricetta("Tagliatelle con la salsa di noci alla piacentina"),
					new Ricetta("Tagliatelle con gli Strigoli"),
					new Ricetta("Taglaitelle verdi"),
					new Ricetta("Lasagne verdi alla bolognese"),
					new Ricetta("Timballo ferrarese"),
					new Ricetta("Tortelli di erbette alla reggiana"),
					new Ricetta("Tortelli di patate"),
					new Ricetta("Agnolotti alle erbe"),
					new Ricetta("Cialzons o Cjalsons cjargnei (agnolotti carnici)"),
					new Ricetta("Gnocchetti de Gries"),
					new Ricetta("Gnocco di pane"),
					new Ricetta("Lasagne ai semi di papavero"),
					new Ricetta("Orzo e funghi"),
					new Ricetta("Paparot (zuppa di granturco e spinaci)"),
					new Ricetta("Polenta alla contadina"),
					new Ricetta("Polenta concia"),
					new Ricetta("Polenta di grano saraceno con cren, mele e ricotta"),
					new Ricetta("Riso e Fasoi alla Friulana"),
					new Ricetta("Risotto con gli scampi"),
					new Ricetta("Tagliolini alla granceola"),
					new Ricetta("Tosella alla panna"),
					new Ricetta("Bucatini all'amatriciana"),
					new Ricetta("Fettuccine alla papalina"),
					new Ricetta("Pasta e patate"),
					new Ricetta("Penne all'arrabbiata"),
					new Ricetta("Spaghetti cacio e pepe"),
					new Ricetta("Spaghetti alla carbonara"),
					new Ricetta("Spaghetti alla puttanesca"),
					new Ricetta("Frascarelli"),
					new Ricetta("Fregnacce alla Castelnovese"),
					new Ricetta("Fregnacce alla Sabinese"),
					new Ricetta("Fregnacce reatine al tartufo"),
					new Ricetta("Gnocchi alla romana"),
					new Ricetta("Gnocchi di patate con puntine di maiale"),
					new Ricetta("Maccheroni con la ricotta"),
					new Ricetta("Pasta e ceci"),
					new Ricetta("Pasta e fagioli"),
					new Ricetta("Patacche"),
					new Ricetta("Rigatoni con la pajata (pagliata)"),
					new Ricetta("Sagne e fagioli"),
					new Ricetta("Spaghetti ajo, ojo e peperoncino (aglio, olio e peperoncino)"),
					new Ricetta("Spaghetti alle vongole veraci"),
					new Ricetta("Stracci di Antrodoco"),
					new Ricetta("Strozzapreti con porcini"),
					new Ricetta("Pasta alla gricia"),
					new Ricetta("Timballo alla ciociara"),
					new Ricetta("Bacialli con pomodori e funghi"),
					new Ricetta("Corzetti alla polceverasca (al sugo)"),
					new Ricetta("Corzetti alla polceverasca (pinoli e maggiorana)"),
					new Ricetta("Crepes al pesto"),
					new Ricetta("Gasse con i piselli (farfalle con i piselli)"),
					new Ricetta("Lasagne al pesto"),
					new Ricetta("Piccagge (Tagliatelle)"),
					new Ricetta("Riso castagne e latte"),
					new Ricetta("Riso con le acciughe"),
					new Ricetta("Trofie di farina di castagne"),
					new Ricetta("Corzetti al Ro"),
					new Ricetta("Farfalle in salsa di noci e pomodori"),
					new Ricetta("Gasse con i piselli"),
					new Ricetta("Linguine ai carciofi"),
					new Ricetta("Linguine con borragine e salsa di noci"),
					new Ricetta("Linguine con pesce e carciofi"),
					new Ricetta("Pansoti (Pansotti) alla genovese"),
					new Ricetta("Risotto al preboggion"),
					new Ricetta("Spaghetti al pesto e gamberetti"),
					new Ricetta("Testaroli"),
					new Ricetta("Trenette al pesto"),
					new Ricetta("Trofie alla ligure"),
					new Ricetta("Trofie di recco"),
					new Ricetta("Orecchiette alla pugliese"),
					new Ricetta("Vermicelli ai frutti di mare"),
					new Ricetta("Tiedda"),
					new Ricetta("Pasta bandiera"),
					new Ricetta("Casoncelli"),
					new Ricetta("Gnocchi al gorgonzola"),
					new Ricetta("Gnocchi burro e salvia"),
					new Ricetta("Risotto alla milanese"),
					new Ricetta("Pizzochheri della Valtellina"),
					new Ricetta("Polenta taragna"),
					new Ricetta("Risotto con la zucca"),
					new Ricetta("Cappelletti in brodo"),
					new Ricetta("Lasagne all'ascolana"),
					new Ricetta("Spaghetti mare e monti"),
					new Ricetta("Cavatelli e carne di maiale"),
					new Ricetta("Pasta con la mollica"),
					new Ricetta("Riso e verza"),
					new Ricetta("Tagliolini di Campobasso"),
					new Ricetta("Risotto alle castagne"),
					new Ricetta("Risotto al barolo"),
					new Ricetta("Agliata"),
					new Ricetta("Gnocchi del Verbano alle erbette verdi"),
					new Ricetta("Panissa"),
					new Ricetta("Ri in cagnon"),
					new Ricetta("Orecchiette alle cime di rapa"),
					new Ricetta("Pasta alla norma"),
					new Ricetta("Pasta con le sarde"),
					new Ricetta("Pasta alla carrettiera"),
					new Ricetta("Bavette con acciuga e mollica"),
					new Ricetta("Spaghetti col cavolfiore fritto"),
					new Ricetta("Pasta col pesto alla trapanese"),
					new Ricetta("Pasta con finocchio 'rizzu'"),
					new Ricetta("Pasta con i tenerumi"),
					new Ricetta("Pasta cu maccu"),
					new Ricetta("Tortelli maremmani"),
					new Ricetta("Bavette all'acciugata"),
					new Ricetta("Maccheroni alla poderana"),
					new Ricetta("Pappardelle al cinghiale"),
					new Ricetta("Pastasciutta alla fornaia"),
					new Ricetta("Risotto alle mele"),
					new Ricetta("Canederli allo speck"),
					new Ricetta("Canederli della Val d'Isarco"),
					new Ricetta("Canederli di grana trentino"),
					new Ricetta("Gnocchi di ortiche"),
					new Ricetta("Spinachspätzle (gnocchetti agli spinaci)"),
					new Ricetta("Farfalle alla frantoia"),
					new Ricetta("Spaghetti al rancetto"),
					new Ricetta("Tagliatelle alla umbra"),
					new Ricetta("Assolette"),
					new Ricetta("Schwoarze Rediene"),
					new Ricetta("Gnocchi alla brava"),
					new Ricetta("Polenta Pasticciata"),
					new Ricetta("Gnocchi all'ampezzana"),
					new Ricetta("Macaroni de sucabaruca"),
					new Ricetta("Risi conzi"),
					new Ricetta("Risi e sparasi alla veneta"),
					new Ricetta("Risotto al tastasal"),
					new Ricetta("Tagliatelle all'agordina"),
					new Ricetta("Polenta con funghi e zucca")

					
					)
			
			);
	
		
	
	
	
	
}
