package dal;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import model.Ricetta;

public class FintoDatabase {

	public static List<Ricetta> secondi = new ArrayList<>(

			Arrays.asList(new Ricetta("Agnello cacio e uova"), new Ricetta("Brodo alla vastese"),
					new Ricetta("Calamari ripieni"), new Ricetta("Scapece alla vastese"), new Ricetta("Arrosticini"),
					new Ricetta("Baccalà  all'abruzzese"), new Ricetta("Cozze allo zafferano"),
					new Ricetta("Fave con guanciale"), new Ricetta("Triglie alla rosetana"),
					new Ricetta("Pollo all'abruzzese"), new Ricetta("Pollo allo zafferano"),
					new Ricetta("Sogliole alla giuliese"), new Ricetta("Tacchino con le castagne"),
					new Ricetta("Triglie ripiene"), new Ricetta("Ndocca"), new Ricetta("Fave e cicorie"),
					new Ricetta("Minestra maritata"), new Ricetta("Cappucci e cicorie"),
					new Ricetta("Lumache all'origano"), new Ricetta("Maiale con le cipolle"),
					new Ricetta("Pollo in salsa piccante"), new Ricetta("Spezzatino di maiale"),
					new Ricetta("Testine di agnello al forno"), new Ricetta("Capretto al forno con i muscari"),
					new Ricetta("Costolette di agnello"), new Ricetta("Cutturidddi"), new Ricetta("Agnello al tegame"),
					new Ricetta("Pecora nel coccio"), new Ricetta("Baccalà  e peperoni"),
					new Ricetta("Baccalà  a ciauredda"), new Ricetta("Baccalà  marinato"),
					new Ricetta("Baccalà  alla lucana"), new Ricetta("Baccalà  crudo"), new Ricetta("Beccacce ripiene"),
					new Ricetta("Involtini di pesce spada"), new Ricetta("Capitone allo spiedo"),
					new Ricetta("Merluzzo al limone"), new Ricetta("Pesce spada con sammurigghiu"),
					new Ricetta("Calamari al brodo"), new Ricetta("Cappone alla calabrese"),
					new Ricetta("Capretto alla silana"), new Ricetta("Aguglie gratinante"),
					new Ricetta("Agnello con pancetta"), new Ricetta("Capretto alla calabrese"),
					new Ricetta("Coniglio alla cacciatora"), new Ricetta("Polpette di stocco"),
					new Ricetta("Tonno alla calabrese"), new Ricetta("Tonno in agrodolce"),
					new Ricetta("Tonno alla marinara"), new Ricetta("Ventresche ripiene"),
					new Ricetta("Carne dei pastori"), new Ricetta("Costolette di agnello alla calabrese"),
					new Ricetta("Tacchino al cedro"), new Ricetta("Lepre all'antica"), new Ricetta("Morzeddu"),
					new Ricetta("Stocco al forno"), new Ricetta("Stocco arrostito"), new Ricetta("Stocco e patate"),
					new Ricetta("Stocco e fagioli"), new Ricetta("Stocco ai funghi"),
					new Ricetta("Vrasciole aru grassu"), new Ricetta("pesce spada arrosto"),
					new Ricetta("Polpette alle mandorle"), new Ricetta("Polpette in agrodolce"),
					new Ricetta("Impepata di cozze"), new Ricetta("Salsicce e friarielli"),
					new Ricetta("Totani e patate"), new Ricetta("Alici alla pescatora"), new Ricetta("Acqua pazza"),
					new Ricetta("Alici alla maruzzella"), new Ricetta("Alici in tortiera"),
					new Ricetta("Aragosta ubriacata"), new Ricetta("Baccalà  alla Bersagliera"),
					new Ricetta("Bocconcini di bufalo con verdure"),
					new Ricetta("Braciolina di pesce spada al pane saporito"),
					new Ricetta("Branzino al forno con patate"), new Ricetta("Arrosto di vitello farcito"),
					new Ricetta("Coniglio alla cacciatora"), new Ricetta("Cotechino in galera"),
					new Ricetta("Capretto piacentino"), new Ricetta("Anguilla alla ferrarese"),
					new Ricetta("Brasato di capocollo"), new Ricetta("Canocchie ripiene alla ravennate"),
					new Ricetta("Coniglio alla reggiana"), new Ricetta("Coniglio in porchetta"),
					new Ricetta("Costolette alla modenese"), new Ricetta("Cotechino con fagioli alla reggiana"),
					new Ricetta("Cotoletta alla bolognese"), new Ricetta("Faraona alla cacciatora alla romagnola"),
					new Ricetta("Filetto alla Bolognese"), new Ricetta("Frizon con salsiccia"),
					new Ricetta("Lumache di Bobbio"), new Ricetta("Petti di tacchino alla bolognese"),
					new Ricetta("Petto di pollo alla bolognese"), new Ricetta("Pollo alla bolognese"),
					new Ricetta("Pollo romagnolo alla cacciatora"), new Ricetta("Rosa di Parma"),
					new Ricetta("Seppie in umido"), new Ricetta("Stufato al latte alla ravennate"),
					new Ricetta("Trippa bolognese"), new Ricetta("Trippa piacentina"), new Ricetta("Valigia reggiana"),
					new Ricetta("Vitello al forno"), new Ricetta("Vitello con carciofi"),
					new Ricetta("Zampone modenese con lenticchie"), new Ricetta("Baccalà  mantecato"),
					new Ricetta("Aringhe alle verdure"), new Ricetta("Gulash"), new Ricetta("Baccalà  alla cappuccina"),
					new Ricetta("Baccalà  alla triestina"), new Ricetta("Branzino con patate e pomodoro"),
					new Ricetta("Brodo di pesce alla dalmata"), new Ricetta("Calamari alla gradesana"),
					new Ricetta("Calamari con piselli"), new Ricetta("Calamari ripieni"),
					new Ricetta("Coniglio con salsa al salame"), new Ricetta("Costine al brodo di polenta"),
					new Ricetta("Cotolette guarnite"), new Ricetta("Faraona alla birra"),
					new Ricetta("Fegato fritto friulano"), new Ricetta("Gallo in umido"),
					new Ricetta("Gamberoni al prosciutto"), new Ricetta("Giambars (gamberi di fiume in padella)"),
					new Ricetta("Lepre in salsa"), new Ricetta("Musà¨t e brovade (cotechino e rape)"),
					new Ricetta("Oca arrosto"), new Ricetta("Pollo fritto"), new Ricetta("Prosciutto in crosta"),
					new Ricetta("Rambasici (involtini di carne e verza)"), new Ricetta("Sarde fritte"),
					new Ricetta("Scampi in bà¹zara"), new Ricetta("Stinco alla carnica"),
					new Ricetta("Abbacchio alla scottadito"), new Ricetta("Coda alla vaccinara"),
					new Ricetta("Saltimbocca alla Romana"), new Ricetta("Trippa alla romana"),
					new Ricetta("Abbacchio alla cacciatora"), new Ricetta("Capretto al rosmarino"),
					new Ricetta("Coniglio alla ciociara"), new Ricetta("Coratella d'abbacchio con i carciofi"),
					new Ricetta("Costolette d'abbacchio panate e fritte"),
					new Ricetta("Costolette di agnello a scottadito"), new Ricetta("Fritto alla romana"),
					new Ricetta("Garofolato"), new Ricetta("Involtini con sedano e carota"),
					new Ricetta("Pollo con i peperoni"), new Ricetta("Salsicce coi broccoli"),
					new Ricetta("Seppie coi piselli"), new Ricetta("Ciuppin"), new Ricetta("Lattughe ripiene"),
					new Ricetta("Baccalà  in agrodolce"), new Ricetta("Baccalà  al verde"),
					new Ricetta("Baccalà  in salsa agliata"), new Ricetta("Baccalà  in zimino"),
					new Ricetta("Boghe a scabeccio"), new Ricetta("Budelline di stocco"),
					new Ricetta("Buridda di seppie"), new Ricetta("Burridda ligure"), new Ricetta("Cappon magro"),
					new Ricetta("Cima genovese"), new Ricetta("Coniglio alla sanremese"),
					new Ricetta("Coniglio alle olive"), new Ricetta("Trippa stufata"), new Ricetta("Groppetti"),
					new Ricetta("Frittelle (Frisceu) di baccalà "), new Ricetta("Totani ripieni"),
					new Ricetta("Manzo alle acciughe"), new Ricetta("Moscardini in umido"),
					new Ricetta("Pesce spada pinoli, olive e capperi"), new Ricetta("Pollo alle barbe di becco"),
					new Ricetta("Seppie in zimino"), new Ricetta("Seppie ripiene di verdure"),
					new Ricetta("Stecchi alla genovese"), new Ricetta("Stecchi cà¶ pin"),
					new Ricetta("Stoccafisso accomodato (accomudou)"), new Ricetta("Stoccafisso brandacujun"),
					new Ricetta("Stracotto di vitello alla ligure"), new Ricetta("Tomaselle (Involtini alla genovese)"),
					new Ricetta("Tonno alla genovese"), new Ricetta("Totani e patate"),
					new Ricetta("Trippa alla sciabecca"), new Ricetta("Pescatrice in terrina"),
					new Ricetta("Polipetti in pignata"), new Ricetta("Agnello alle olive"),
					new Ricetta("Ciciones con salsiccia"), new Ricetta("Culiogiones di patate"),
					new Ricetta("Gnocchetti sardi al pecorino"), new Ricetta("Cinghiale al Cannonau"),
					new Ricetta("Porceddu allo spiedo"), new Ricetta("Anatra lessa al mirto"), new Ricetta("Bombas"),
					new Ricetta("Cossa prena"), new Ricetta("Brasato"), new Ricetta("Cappone ripieno"),
					new Ricetta("Capretto alla bresciana"), new Ricetta("Cassoeula"),
					new Ricetta("Cotolette alla milanese"), new Ricetta("Baccalà  in salsa verde"),
					new Ricetta("Braciole di maiale"), new Ricetta("Brodetto all'anconetana"),
					new Ricetta("Pollo alla cacciatora"), new Ricetta("Merluzzo alla marchigiana"),
					new Ricetta("Bollito di maiale e riso"), new Ricetta("Brodo alla termolese"),
					new Ricetta("Minestra di zucchine"), new Ricetta("Zuppa di pesce"), new Ricetta("Affunniatelle"),
					new Ricetta("Agnello e piselli"), new Ricetta("Baccalà  con patate"),
					new Ricetta("Baccalà  fritto"), new Ricetta("Capra alla molisana"),
					new Ricetta("Polpette di formaggio"), new Ricetta("Pollo all'albese"),
					new Ricetta("Vitello tonnato"), new Ricetta("Brasato al barolo"),
					new Ricetta("Trota ai profumi alpini"), new Ricetta("Baccalà  alla ghiotta"),
					new Ricetta("Polpo in umido"), new Ricetta("Tonno stufato"),
					new Ricetta("Tunnina ammarinata (tonno in agrodolce)"), new Ricetta("Capretto al forno"),
					new Ricetta("Carcagnolu"), new Ricetta("Carne alla pizzaiola"),
					new Ricetta("Coniglio alla cacciatora"), new Ricetta("Merluzzo al forno"),
					new Ricetta("Muscolo lesso"), new Ricetta("Pollo agglassato"), new Ricetta("Salsiccia al ragà¹"),
					new Ricetta("Tunnina  fritta"), new Ricetta("Trippa alla fiorentina"),
					new Ricetta("Agnello pillottato al forno"), new Ricetta("Arista di maiale arrosto"),
					new Ricetta("Baccalà  con le patate alla Trentina"), new Ricetta("Agnello in salsa tirolese"),
					new Ricetta("Costata gratinata con midollo"), new Ricetta("Filetto di manzo ripieno con cicoria"),
					new Ricetta("Rosticciata di carne e patate"), new Ricetta("Stufato dâ€™agnello"),
					new Ricetta("Arista di maiale all'umbra"), new Ricetta("Coratella"),
					new Ricetta("Anatra muta in porchetta"), new Ricetta("Anatra selvatica al sugo"),
					new Ricetta("Arista al cavolo nero e melograno"), new Ricetta("Bistecca del curato "),
					new Ricetta("Carne al vino bianco"), new Ricetta("Cinghiale ai frutti di bosco"),
					new Ricetta("Costolette alla valdostana"), new Ricetta("Fegato alla paesana"),
					new Ricetta("Petti di pollo alla valdostana"), new Ricetta("Pollo al forno con salsa ai fagioli"),
					new Ricetta("Oca arrosto con mele e castagne"), new Ricetta("Salsicce all'aceto"),
					new Ricetta("Folpetti alla veneziana (polpetti alla veneziana)"),
					new Ricetta("Bisato su la griglia (anguilla alla griglia)"), new Ricetta("Fegato alla veneziana"),
					new Ricetta("Alborelle fritte")));

	public static List<Ricetta> ricetteBase = new ArrayList<>(

			Arrays.asList(new Ricetta("Cannarozzetti allo zafferano"), new Ricetta("Spaghetti all'abruzzese"),
					new Ricetta("Timballo ai finocchi"), new Ricetta("Fettuccine all'abruzzese"),
					new Ricetta("Cannelloni all'abruzzese"), new Ricetta("Fettuccine ai peperoni"),
					new Ricetta("Fregnacce"), new Ricetta("Maccheroni alla molinara"),
					new Ricetta("Maccheroni alla chitarra"), new Ricetta("Tagliatelle al sugo di lumache"),
					new Ricetta("Tagliatelle al baccalà "), new Ricetta("Pasta e fagioli"),
					new Ricetta("Cavatelli con pecorino e rucola"), new Ricetta("Cavatelli alle cime di rapa"),
					new Ricetta("Fusilli alla salsiccia"), new Ricetta("Fusilli con la mollica"),
					new Ricetta("Grano al sugo"), new Ricetta("Orecchiette alla materana"),
					new Ricetta("Lagane e ceci"), new Ricetta("Orecchiette con le rape"),
					new Ricetta("Spaghetti di maratea"), new Ricetta("Strozzapreti alla potentina"),
					new Ricetta("Pasta ai ricci di mare"), new Ricetta("Pasta e Broccoli"),
					new Ricetta("Pennette alle Verdure Piccanti"), new Ricetta("Cannaruozzi 'ncipuddati"),
					new Ricetta("Spaghetti con carciofi"), new Ricetta("Riso alle mandorle"),
					new Ricetta("Tagliatelle alla reggina"), new Ricetta("Bucatini con la mollica"),
					new Ricetta("Bucatini con lo stocco"), new Ricetta("Bucatini col finocchietto selvatico"),
					new Ricetta("Spaghetti con le alici"), new Ricetta("Fusilli al cedro"),
					new Ricetta("Maccaruni ara turanisi"), new Ricetta("Ravioli con lo stocco"),
					new Ricetta("Risotto con lo stocco"), new Ricetta("Spaghetti al nero di seppia"),
					new Ricetta("Lagane e ceci"), new Ricetta("Gnocchi alla caprese"),
					new Ricetta("Maltagliati alla napoletana"), new Ricetta("Spaghetti con le vongole"),
					new Ricetta("Pasta e castagne"), new Ricetta("Spaghetti ai firarielli"),
					new Ricetta("Pasta mista con fave e pancetta"), new Ricetta("Tagliatelle al ragà¹"),
					new Ricetta("Tortellini alla bolognese"), new Ricetta("Gnocchi di patate"),
					new Ricetta("Cappellacci di zucca"), new Ricetta("Bassotti"),
					new Ricetta("Garganelli con ragà¹ alla romagnola"), new Ricetta("Gramigna con la salsiccia"),
					new Ricetta("Anolini di carne parmensi"), new Ricetta("Cappelletti alla bolognese"),
					new Ricetta("Cappelletti all'emiliana"), new Ricetta("Cappelletti di magro romagnoli"),
					new Ricetta("Cappelletti pasticciati"), new Ricetta("Cappelletti romagnoli"),
					new Ricetta("Passatelli reggiani"), new Ricetta("Pasta rasa reggiana"),
					new Ricetta("Risotto alla parmigiana"), new Ricetta("Risotto all'imolese"),
					new Ricetta("Risotto con la zucca"),
					new Ricetta("Tagliatelle con la salsa di noci alla piacentina"),
					new Ricetta("Tagliatelle con gli Strigoli"), new Ricetta("Taglaitelle verdi"),
					new Ricetta("Lasagne verdi alla bolognese"), new Ricetta("Timballo ferrarese"),
					new Ricetta("Tortelli di erbette alla reggiana"), new Ricetta("Tortelli di patate"),
					new Ricetta("Agnolotti alle erbe"), new Ricetta("Cialzons o Cjalsons cjargnei (agnolotti carnici)"),
					new Ricetta("Gnocchetti de Gries"), new Ricetta("Gnocco di pane"),
					new Ricetta("Lasagne ai semi di papavero"), new Ricetta("Orzo e funghi"),
					new Ricetta("Paparot (zuppa di granturco e spinaci)"), new Ricetta("Polenta alla contadina"),
					new Ricetta("Polenta concia"), new Ricetta("Polenta di grano saraceno con cren, mele e ricotta"),
					new Ricetta("Riso e Fasoi alla Friulana"), new Ricetta("Risotto con gli scampi"),
					new Ricetta("Tagliolini alla granceola"), new Ricetta("Tosella alla panna"),
					new Ricetta("Bucatini all'amatriciana"), new Ricetta("Fettuccine alla papalina"),
					new Ricetta("Pasta e patate"), new Ricetta("Penne all'arrabbiata"),
					new Ricetta("Spaghetti cacio e pepe"), new Ricetta("Spaghetti alla carbonara"),
					new Ricetta("Spaghetti alla puttanesca"), new Ricetta("Frascarelli"),
					new Ricetta("Fregnacce alla Castelnovese"), new Ricetta("Fregnacce alla Sabinese"),
					new Ricetta("Fregnacce reatine al tartufo"), new Ricetta("Gnocchi alla romana"),
					new Ricetta("Gnocchi di patate con puntine di maiale"), new Ricetta("Maccheroni con la ricotta"),
					new Ricetta("Pasta e ceci"), new Ricetta("Pasta e fagioli"), new Ricetta("Patacche"),
					new Ricetta("Rigatoni con la pajata (pagliata)"), new Ricetta("Sagne e fagioli"),
					new Ricetta("Spaghetti ajo, ojo e peperoncino (aglio, olio e peperoncino)"),
					new Ricetta("Spaghetti alle vongole veraci"), new Ricetta("Stracci di Antrodoco"),
					new Ricetta("Strozzapreti con porcini"), new Ricetta("Pasta alla gricia"),
					new Ricetta("Timballo alla ciociara"), new Ricetta("Bacialli con pomodori e funghi"),
					new Ricetta("Corzetti alla polceverasca (al sugo)"),
					new Ricetta("Corzetti alla polceverasca (pinoli e maggiorana)"), new Ricetta("Crepes al pesto"),
					new Ricetta("Gasse con i piselli (farfalle con i piselli)"), new Ricetta("Lasagne al pesto"),
					new Ricetta("Piccagge (Tagliatelle)"), new Ricetta("Riso castagne e latte"),
					new Ricetta("Riso con le acciughe"), new Ricetta("Trofie di farina di castagne"),
					new Ricetta("Corzetti al Ro"), new Ricetta("Farfalle in salsa di noci e pomodori"),
					new Ricetta("Gasse con i piselli"), new Ricetta("Linguine ai carciofi"),
					new Ricetta("Linguine con borragine e salsa di noci"), new Ricetta("Linguine con pesce e carciofi"),
					new Ricetta("Pansoti (Pansotti) alla genovese"), new Ricetta("Risotto al preboggion"),
					new Ricetta("Spaghetti al pesto e gamberetti"), new Ricetta("Testaroli"),
					new Ricetta("Trenette al pesto"), new Ricetta("Trofie alla ligure"), new Ricetta("Trofie di recco"),
					new Ricetta("Orecchiette alla pugliese"), new Ricetta("Vermicelli ai frutti di mare"),
					new Ricetta("Tiedda"), new Ricetta("Pasta bandiera"), new Ricetta("Casoncelli"),
					new Ricetta("Gnocchi al gorgonzola"), new Ricetta("Gnocchi burro e salvia"),
					new Ricetta("Risotto alla milanese"), new Ricetta("Pizzochheri della Valtellina"),
					new Ricetta("Polenta taragna"), new Ricetta("Risotto con la zucca"),
					new Ricetta("Cappelletti in brodo"), new Ricetta("Lasagne all'ascolana"),
					new Ricetta("Spaghetti mare e monti"), new Ricetta("Cavatelli e carne di maiale"),
					new Ricetta("Pasta con la mollica"), new Ricetta("Riso e verza"),
					new Ricetta("Tagliolini di Campobasso"), new Ricetta("Risotto alle castagne"),
					new Ricetta("Risotto al barolo"), new Ricetta("Agliata"),
					new Ricetta("Gnocchi del Verbano alle erbette verdi"), new Ricetta("Panissa"),
					new Ricetta("Ri in cagnon"), new Ricetta("Orecchiette alle cime di rapa"),
					new Ricetta("Pasta alla norma"), new Ricetta("Pasta con le sarde"),
					new Ricetta("Pasta alla carrettiera"), new Ricetta("Bavette con acciuga e mollica"),
					new Ricetta("Spaghetti col cavolfiore fritto"), new Ricetta("Pasta col pesto alla trapanese"),
					new Ricetta("Pasta con finocchio 'rizzu'"), new Ricetta("Pasta con i tenerumi"),
					new Ricetta("Pasta cu maccu"), new Ricetta("Tortelli maremmani"),
					new Ricetta("Bavette all'acciugata"), new Ricetta("Maccheroni alla poderana"),
					new Ricetta("Pappardelle al cinghiale"), new Ricetta("Pastasciutta alla fornaia"),
					new Ricetta("Risotto alle mele"), new Ricetta("Canederli allo speck"),
					new Ricetta("Canederli della Val d'Isarco"), new Ricetta("Canederli di grana trentino"),
					new Ricetta("Gnocchi di ortiche"), new Ricetta("Spinachspatzle (gnocchetti agli spinaci)"),
					new Ricetta("Farfalle alla frantoia"), new Ricetta("Spaghetti al rancetto"),
					new Ricetta("Tagliatelle alla umbra"), new Ricetta("Assolette"), new Ricetta("Schwoarze Rediene"),
					new Ricetta("Gnocchi alla brava"), new Ricetta("Polenta Pasticciata"),
					new Ricetta("Gnocchi all'ampezzana"), new Ricetta("Macaroni de sucabaruca"),
					new Ricetta("Risi conzi"), new Ricetta("Risi e sparasi alla veneta"),
					new Ricetta("Risotto al tastasal"), new Ricetta("Tagliatelle all'agordina"),
					new Ricetta("Polenta con funghi e zucca")

			)

	);

}
